# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-6, -1, 891, 661))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.main_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 161, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(5)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.date_label = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.date_label.setFont(font)
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setIndent(13)
        self.date_label.setObjectName("date_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.date_label)
        self.date_input = QtWidgets.QDateEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_input.sizePolicy().hasHeightForWidth())
        self.date_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_input.setFont(font)
        self.date_input.setCalendarPopup(True)
        self.date_input.setObjectName("date_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.date_input)
        self.weight_label = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight_label.sizePolicy().hasHeightForWidth())
        self.weight_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.weight_label.setFont(font)
        self.weight_label.setAlignment(QtCore.Qt.AlignCenter)
        self.weight_label.setObjectName("weight_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.weight_label)
        self.weight_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight_input.sizePolicy().hasHeightForWidth())
        self.weight_input.setSizePolicy(sizePolicy)
        self.weight_input.setMinimumSize(QtCore.QSize(65, 0))
        self.weight_input.setMaximumSize(QtCore.QSize(8000, 16777215))
        self.weight_input.setBaseSize(QtCore.QSize(25000, 25000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.weight_input.setFont(font)
        self.weight_input.setMaxLength(5)
        self.weight_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weight_input.setObjectName("weight_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.weight_input)
        self.calories_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.calories_label.setFont(font)
        self.calories_label.setObjectName("calories_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.calories_label)
        self.calories_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calories_input.sizePolicy().hasHeightForWidth())
        self.calories_input.setSizePolicy(sizePolicy)
        self.calories_input.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calories_input.setFont(font)
        self.calories_input.setMaxLength(6)
        self.calories_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.calories_input.setObjectName("calories_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.calories_input)
        self.protein_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.protein_label.setFont(font)
        self.protein_label.setObjectName("protein_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.protein_label)
        self.protein_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protein_input.sizePolicy().hasHeightForWidth())
        self.protein_input.setSizePolicy(sizePolicy)
        self.protein_input.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.protein_input.setFont(font)
        self.protein_input.setMaxLength(5)
        self.protein_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.protein_input.setObjectName("protein_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.protein_input)
        self.carbs_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.carbs_label.setFont(font)
        self.carbs_label.setObjectName("carbs_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.carbs_label)
        self.carbs_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carbs_input.sizePolicy().hasHeightForWidth())
        self.carbs_input.setSizePolicy(sizePolicy)
        self.carbs_input.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.carbs_input.setFont(font)
        self.carbs_input.setMaxLength(5)
        self.carbs_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.carbs_input.setObjectName("carbs_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.carbs_input)
        self.steps_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.steps_label.setFont(font)
        self.steps_label.setObjectName("steps_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.steps_label)
        self.steps_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.steps_input.sizePolicy().hasHeightForWidth())
        self.steps_input.setSizePolicy(sizePolicy)
        self.steps_input.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.steps_input.setFont(font)
        self.steps_input.setMaxLength(5)
        self.steps_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.steps_input.setObjectName("steps_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.steps_input)
        self.burned_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.burned_label.setFont(font)
        self.burned_label.setObjectName("burned_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.burned_label)
        self.burned_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.burned_input.sizePolicy().hasHeightForWidth())
        self.burned_input.setSizePolicy(sizePolicy)
        self.burned_input.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.burned_input.setFont(font)
        self.burned_input.setMaxLength(3)
        self.burned_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.burned_input.setObjectName("burned_input")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.burned_input)
        self.sleep_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sleep_label.setFont(font)
        self.sleep_label.setObjectName("sleep_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.sleep_label)
        self.sleep_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sleep_input.sizePolicy().hasHeightForWidth())
        self.sleep_input.setSizePolicy(sizePolicy)
        self.sleep_input.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sleep_input.setFont(font)
        self.sleep_input.setMaxLength(4)
        self.sleep_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sleep_input.setObjectName("sleep_input")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.sleep_input)
        self.save_button = QtWidgets.QToolButton(self.main_tab)
        self.save_button.setGeometry(QtCore.QRect(110, 310, 31, 31))
        self.save_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/imgs/add_icon.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.save_button.setIcon(icon)
        self.save_button.setIconSize(QtCore.QSize(25, 25))
        self.save_button.setObjectName("save_button")
        self.weekly_data = QtWidgets.QGroupBox(self.main_tab)
        self.weekly_data.setGeometry(QtCore.QRect(210, 30, 661, 541))
        self.weekly_data.setFlat(False)
        self.weekly_data.setCheckable(False)
        self.weekly_data.setObjectName("weekly_data")
        self.gridLayoutWidget = QtWidgets.QWidget(self.weekly_data)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 81, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget.addTab(self.main_tab, "")
        self.image_tab = QtWidgets.QWidget()
        self.image_tab.setObjectName("image_tab")
        self.pic = QtWidgets.QLabel(self.image_tab)
        self.pic.setGeometry(QtCore.QRect(60, 60, 471, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic.sizePolicy().hasHeightForWidth())
        self.pic.setSizePolicy(sizePolicy)
        self.pic.setFrameShape(QtWidgets.QFrame.Box)
        self.pic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pic.setText("")
        self.pic.setObjectName("pic")
        self.tabWidget.addTab(self.image_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.date_input.setDisplayFormat(_translate("MainWindow", "MM/dd/yy"))
        self.weight_label.setText(_translate("MainWindow", "Weight"))
        self.calories_label.setText(_translate("MainWindow", "Calories"))
        self.protein_label.setText(_translate("MainWindow", "Protein"))
        self.carbs_label.setText(_translate("MainWindow", "Carbs"))
        self.steps_label.setText(_translate("MainWindow", "Steps"))
        self.burned_label.setText(_translate("MainWindow", "Burned"))
        self.sleep_label.setText(_translate("MainWindow", "Sleep"))
        self.save_button.setText(_translate("MainWindow", "..."))
        self.weekly_data.setTitle(_translate("MainWindow", "Weekly Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), _translate("MainWindow", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.image_tab), _translate("MainWindow", "Images"))
