# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Nutrition Log")
        MainWindow.resize(490, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 501, 541))
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tabWidget.setObjectName("tabWidget")
        self.input_tab = QtWidgets.QWidget()
        self.input_tab.setObjectName("input_tab")
        self.date_label = QtWidgets.QLabel(self.input_tab)
        self.date_label.setGeometry(QtCore.QRect(90, 40, 31, 18))
        self.date_label.setObjectName("date_label")
        self.calories_label = QtWidgets.QLabel(self.input_tab)
        self.calories_label.setGeometry(QtCore.QRect(80, 140, 58, 18))
        self.calories_label.setObjectName("calories_label")
        self.other_kcal_label = QtWidgets.QLabel(self.input_tab)
        self.other_kcal_label.setGeometry(QtCore.QRect(20, 340, 121, 20))
        self.other_kcal_label.setObjectName("other_kcal_label")
        self.protein_label = QtWidgets.QLabel(self.input_tab)
        self.protein_label.setGeometry(QtCore.QRect(80, 190, 51, 18))
        self.protein_label.setObjectName("protein_label")
        self.sleep_label = QtWidgets.QLabel(self.input_tab)
        self.sleep_label.setGeometry(QtCore.QRect(90, 390, 41, 18))
        self.sleep_label.setObjectName("sleep_label")
        self.date = QtWidgets.QDateEdit(self.input_tab)
        self.date.setGeometry(QtCore.QRect(150, 30, 111, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date.sizePolicy().hasHeightForWidth())
        self.date.setSizePolicy(sizePolicy)
        self.date.setCalendarPopup(True)
        self.date.setObjectName("date")
        self.steps_label = QtWidgets.QLabel(self.input_tab)
        self.steps_label.setGeometry(QtCore.QRect(90, 290, 41, 18))
        self.steps_label.setObjectName("steps_label")
        self.save = QtWidgets.QPushButton(self.input_tab)
        self.save.setGeometry(QtCore.QRect(150, 440, 71, 34))
        self.save.setObjectName("save")
        self.weight_label = QtWidgets.QLabel(self.input_tab)
        self.weight_label.setGeometry(QtCore.QRect(80, 90, 51, 20))
        self.weight_label.setObjectName("weight_label")
        self.weight_input = QtWidgets.QLineEdit(self.input_tab)
        self.weight_input.setGeometry(QtCore.QRect(150, 90, 113, 32))
        self.weight_input.setObjectName("weight_input")
        self.calories_input = QtWidgets.QLineEdit(self.input_tab)
        self.calories_input.setGeometry(QtCore.QRect(150, 140, 113, 32))
        self.calories_input.setInputMethodHints(QtCore.Qt.ImhNone)
        self.calories_input.setObjectName("calories_input")
        self.protein_input = QtWidgets.QLineEdit(self.input_tab)
        self.protein_input.setGeometry(QtCore.QRect(150, 190, 113, 32))
        self.protein_input.setObjectName("protein_input")
        self.other_kcal_input = QtWidgets.QLineEdit(self.input_tab)
        self.other_kcal_input.setGeometry(QtCore.QRect(150, 340, 113, 32))
        self.other_kcal_input.setObjectName("other_kcal_input")
        self.steps_input = QtWidgets.QLineEdit(self.input_tab)
        self.steps_input.setGeometry(QtCore.QRect(150, 290, 113, 32))
        self.steps_input.setObjectName("steps_input")
        self.sleep_input = QtWidgets.QLineEdit(self.input_tab)
        self.sleep_input.setGeometry(QtCore.QRect(150, 390, 113, 32))
        self.sleep_input.setObjectName("sleep_input")
        self.carbs_input = QtWidgets.QLineEdit(self.input_tab)
        self.carbs_input.setGeometry(QtCore.QRect(150, 240, 113, 32))
        self.carbs_input.setObjectName("carbs_input")
        self.carbs_label = QtWidgets.QLabel(self.input_tab)
        self.carbs_label.setGeometry(QtCore.QRect(90, 240, 41, 20))
        self.carbs_label.setObjectName("carbs_label")
        self.tabWidget.addTab(self.input_tab, "")
        self.snapshot_tab = QtWidgets.QWidget()
        self.snapshot_tab.setObjectName("snapshot_tab")
        self.refresh = QtWidgets.QPushButton(self.snapshot_tab)
        self.refresh.setGeometry(QtCore.QRect(10, 50, 71, 23))
        self.refresh.setObjectName("refresh")



        ###############
        ##   TABLE   ##
        ###############
        self.snapshot_table = QtWidgets.QTableWidget(self.snapshot_tab)   
        self.snapshot_table.setGeometry(QtCore.QRect(10, 80, 481, 361))
        self.snapshot_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.snapshot_table.setObjectName("snapshot_table")
        self.snapshot_table.setGridStyle(QtCore.Qt.SolidLine)
        self.snapshot_table.setRowCount(3)
        self.snapshot_table.setColumnCount(8)
        ###############
        ###############



        self.tabWidget.addTab(self.snapshot_tab, "")
        self.calendar_tab = QtWidgets.QWidget()
        self.calendar_tab.setObjectName("calendar_tab")
        self.tabWidget.addTab(self.calendar_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.date)
        MainWindow.setTabOrder(self.date, self.weight_input)
        MainWindow.setTabOrder(self.weight_input, self.calories_input)
        MainWindow.setTabOrder(self.calories_input, self.protein_input)
        MainWindow.setTabOrder(self.protein_input, self.carbs_input)
        MainWindow.setTabOrder(self.carbs_input, self.steps_input)
        MainWindow.setTabOrder(self.steps_input, self.other_kcal_input)
        MainWindow.setTabOrder(self.other_kcal_input, self.sleep_input)
        MainWindow.setTabOrder(self.sleep_input, self.save)
        MainWindow.setTabOrder(self.save, self.snapshot_table)
        MainWindow.setTabOrder(self.snapshot_table, self.refresh)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.calories_label.setText(_translate("MainWindow", "Calories"))
        self.other_kcal_label.setText(_translate("MainWindow", "Other kcal burned"))
        self.protein_label.setText(_translate("MainWindow", "Protein"))
        self.sleep_label.setText(_translate("MainWindow", "Sleep"))
        self.date.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy"))
        self.steps_label.setText(_translate("MainWindow", "Steps"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.weight_label.setText(_translate("MainWindow", "Weight"))
        self.carbs_label.setText(_translate("MainWindow", "Carbs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_tab), _translate("MainWindow", "Tab 1"))
        self.refresh.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.snapshot_tab), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calendar_tab), _translate("MainWindow", "Page"))
